# This is a basic workflow to help you get started with Actions

name: Build Tegra Server image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "20" branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tegra-classic:
    strategy:
      matrix:
        arch: [ ARM64 ]
    runs-on: [ self-hosted , "${{ matrix.arch }}" ]
    steps:
    - name: Install pre-requisites
      run: |
        sudo apt install -y git germinate devscripts debootstrap devscripts
    - name: Install ubuntu-image
      run: |
        sudo snap install --classic --channel latest/edge ubuntu-image
    - name: Get image-definition
      run: |
        git clone -b jammy https://git.launchpad.net/ubuntu-images
    - name: Build
      run: |
        sudo /snap/bin/ubuntu-image classic -w work -O output ubuntu-server-tegra-igx.yaml
    - uses: actions/upload-artifact@v4
      with:
        name: image
        path: ubuntu-22.04-preinstalled-server-arm64+tegra-igx.img
